### ISSUE TITLE
Rename readthedocs project and update link associated with GitHub project

### ISSUE THREAD

**Issue by jcfr** [girder/slicer_package_manager#25]
http://slicer-extension-manager.readthedocs.io/en/latest/ -> http://slicer-package-manager.readthedocs.io/en/latest/

**Comment by Pierre-Assemat** [comment]
Done! I just wait to see the build success before closing this issue.

**Comment by Pierre-Assemat** [comment]
Also I need to delete the project from readthedoc to change the URL

**Comment by jcfr** [comment]
> Also I need to delete the project from readthedoc to change the URL

Can you do it yourself or do you need someone with more credentials ?

**Comment by Pierre-Assemat** [comment]
I did it already
