### ISSUE TITLE
Review what would need to be changed to download.slicer.org

### ISSUE THREAD

**Issue by jcfr** [girder/slicer_package_manager#56]
The front end for presenting Slicer packages is https://download.slicer.org/

The associated code can be found here: https://github.com/mhalle/slicer4-download

### Step 1: API update

Update slicer4-download so that it can work with the API of the slicer_package_manager server.

cc: @Pierre-Assemat  

@mhalle: Would it be possible to setup a `test-download.slicer.org` that we could update our-self to test ? 

### Step 2: Stats

Investigate how we could also keep track of more sophisticated stats for extension packages

The `download.slicer.org` currently takes care of generating the download stats: https://download.slicer.org/download-stats/ 

The download stats are first gathered by parsing the Apache log and keeping track of the results in a local sqlite database.  It also look the stats can be exported to json.

@mhalle We would like to also support similar stats for the new extensions infrastructure. We were thinking to generalize your work and keep track of stats for both application packages and extension packages.

**Comment by mhalle** [comment]
If y'all want to take this part of the slicer infrastructure over, sounds great to me.  I've just got done consolidating the code into two github repositories, one for the download piece and one for the stats.  The slicer4-download piece includes the back-end flask server for the download page and two cli programs that collect statistics from kitware and the apache logs for both the download page and the stats page. These run from cron.  The download-stats background program puts it cumulative statistics in an sqlite file, and exports a condensed JSON file that the stats page uses.

This seems like a perfect opportunity for someone else to take this project over, if that makes sense. 

Let me know how you want to proceed.
--Mike

**Comment by jcfr** [comment]
Closing. The infrastructure has been transitioning and updated.
See https://github.com/Slicer/slicer_download#history
